spring:
  application:
    name: reservation-api
  profiles:
    active: local
### Create another application_local.yml file, copy the text below and uncomment it ###
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:h2:C:/Users/User/Documents/reservationapi/src/main/resources/database/reservations
#     OR (for in-memory)
#    url: jdbc:h2:mem:reservations
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true