###GET ALL request to Reservations API
GET http://localhost:8080/api/reservations

<> 2024-10-16T085144.500.json

### GET request to Reservations API

@id = 2

GET http://localhost:8080/api/reservations/{{id}}

### POST request to Reservations API

@name = "Zaky Coco"
@phone_number = "+639334466890"
@email = "zaky@coco.melon"
@reservation_date = "2024-11-17"
@reservation_time = "09:30:00"
@number_of_guests = 5
@contact_methods = ["SMS","Phone"]



POST http://localhost:8080/api/reservations
Content-Type: application/json

{
  "name": {{name}},
  "phone_number": {{phone_number}},
  "email": {{email}},
  "reservation_date": {{reservation_date}},
  "reservation_time": {{reservation_time}},
  "number_of_guests": {{number_of_guests}},
  "contact_methods": {{contact_methods}}
}

